feat(GetEntrances): get entrance of a country or a massif with data q…
GrottoCenter/grottocenter-api pull request #1115
Opened 2023-01-27 08:55 UTC by MargotGeorget

…uality value computed

## 🤔 What

Added routes to get entrances of a massif or a country. We computed the quality of the data registered for each entrances. 
We created a new file in the utils folder to put the different functions use to compute the quality of the data.

2023-01-29 23:23 UTC, bsoufflet requested changes

2023-01-29 23:23 UTC, bsoufflet commented on api/services/DataQualityComputeService.js
> +  getLatestDateOfUpdateAndNbContributionsOfEachEntrancesOfAMassif: async (
Trop long, ca devient impossible à lire ;)
getEntrancesByMassifWithQuality ou un truc du genre ;)

2023-01-29 23:23 UTC, bsoufflet commented on api/services/DataQualityComputeService.js
> +   * @param {string} countryId
@param {string} countryId alpha-2 code

2023-01-29 23:23 UTC, bsoufflet commented on api/utils/computeEntranceDataQuality.js
> +/**
Il me semblerait bien d'écrire en commentaire de ce fichier un résumé des règles de calculs du "quality score"

2023-01-29 23:23 UTC, bsoufflet commented on api/utils/computeEntranceDataQuality.js
> +  const [year, month, day] = [now.getFullYear(), now.getMonth(), now.getDate()];
Nous avons cette lib de dispo dans package.json : date-io/date-fns
Tu peux donc simplifier un peu cette fonction comme cela : 
```
const { subYears } = require('@date-io/date-fns');
...
const now = new Date();
if (entityDate) {
    if (entityDate > subYears(now, 2) {
        return 7;
```
https://date-fns.org/v2.29.3/docs/subYears

2023-01-31 13:43 UTC, Ophelux commented on sql/4_materialized_views.sql
> +  (COUNT(DISTINCT e.date_inscription)+ COUNT(DISTINCT e.date_reviewed)) as general_nb_contributions,
D'après ce message sur le document partagé à tous en début de projet, on a interprété que l'utilisation de la table d'historisation n'était pas nécessaire, on utilisait uniquement la table t_entrance. 
En effet, s'il y a une date reviewed, c'est qu'il y a au moins 2 contributeurs, ce qui rentre dans nos critères de calcul: 0, 1 ou 2+ contributeurs. 
![image](https://user-images.githubusercontent.com/38314225/215775686-a0e815a3-8b89-46b2-a547-de5ac7ecc6f1.png)

2023-01-31 14:08 UTC, Ophelux commented on sql/4_materialized_views.sql
> +
Nous avons rajouté une ligne de création d'index dans le fichier 0_views.sql pour la vue matérialisée v_data_quality_compute_entrance, le CONCURRENTLY pourra ainsi être appliqué. Nous allons également ajouter des index pou toutes les vues.

2023-01-31 14:21 UTC, Ophelux commented on api/services/DataQualityComputeService.js
> +const GET_LASTEST_DATE_OF_UPDATE_AND_NB_CONTRIBUTIONS_OF_A_MASSIF = `
Peut être pouvons nous mettre `GET_ENTRANCES_INFORMATIONS_OF_A_MASSIF` car nous récupérons de quoi calculer la qualité pour chaque entrance mais pas la qualité en elle-même.

2023-01-31 14:22 UTC, Ophelux commented on api/services/DataQualityComputeService.js
> +const GET_LASTEST_DATE_OF_UPDATE_AND_NB_CONTRIBUTIONS_OF_A_COUNTRY = `
`GET_ENTRANCES_INFORMATIONS_OF_A_COUNTRY` ?

2023-01-31 14:25 UTC, Ophelux commented on api/services/DataQualityComputeService.js
> +  getLatestDateOfUpdateAndNbContributionsOfEachEntrancesOfAMassif: async (
'getEntranceInformationOfAMassif' ?

2023-02-01 00:00 UTC, bsoufflet commented on api/services/DataQualityComputeService.js
> +const GET_LASTEST_DATE_OF_UPDATE_AND_NB_CONTRIBUTIONS_OF_A_COUNTRY = `
oui par exemple ;)

2023-02-01 00:02 UTC, bsoufflet commented on api/services/DataQualityComputeService.js
> +  getLatestDateOfUpdateAndNbContributionsOfEachEntrancesOfAMassif: async (
Je préfère getEntrancesWithQualityByMassif ... Mais faites ce que vous préférez tant que ce n'est pas un nom de 200 caractères ;)

2023-02-01 17:10 UTC, bsoufflet requested changes

2023-02-01 17:10 UTC, bsoufflet commented on assets/swaggerV1.yaml
> +  '/massifs/{id}/entrances-data-quality':
Les routes ont changé et doivent etre changé ici il semble :)

2023-02-01 17:10 UTC, bsoufflet commented on assets/swaggerV1.yaml
> +  '/countries/{id}/entrances-data-quality':
Les routes ont changé et doivent etre changé ici il semble :)

2023-02-01 17:10 UTC, bsoufflet commented on package.json
> +    "date-fns": "^2.29.3",
On a déjà @date-io/date-fn de dispo en ligne 12 donc pas besoin de cela je pense non ?

2023-02-01 17:10 UTC, bsoufflet commented on sql/4_materialized_views.sql
> +CREATE INDEX index_data_quality_compute_entrance ON v_data_quality_compute_entrance(id_entrance);
CREATE UNIQUE INDEX (pour que ca fonctionne avec le CONCURRENTLY)

2023-02-01 17:10 UTC, bsoufflet commented on sql/4_materialized_views.sql
> +CREATE INDEX index_massif_info ON v_massif_info(id_cave);
CREATE UNIQUE INDEX (pour que ca fonctionne avec le CONCURRENTLY)

2023-02-01 17:10 UTC, bsoufflet commented on sql/4_materialized_views.sql
> +CREATE INDEX index_country_info ON v_country_info(id_cave);
CREATE UNIQUE INDEX (pour que ca fonctionne avec le CONCURRENTLY)

2023-02-02 09:32 UTC, MargotGeorget commented on package.json
> +    "date-fns": "^2.29.3",
Nous avions essayé mais nous n'avons pas réussi à utiliser la fonction subYears avec @date-io/date-fn

2023-02-02 21:19 UTC, bsoufflet commented on package.json
> +    "date-fns": "^2.29.3",
Je viens de faire le point sur nos lib de date et on a aussi moment (dont on ne peut pas se passer actuellement). J'ai donc supprimer les 2 date-fns et j'ai changé votre code pour utiliser Moment ;)

2023-02-02 21:29 UTC, bsoufflet approved these changes

2023-02-02 21:29 UTC, merged