Get all snapshots of an entrance
GrottoCenter/grottocenter-api pull request #1116
Opened 2023-01-27 14:31 UTC by julien-vendran

## 🤔 What

Add a route for the general page of snapshot. 
It contains all snapshots related to an entrance (Entrances, Locations, Descriptions, ...)

2023-01-29 23:49 UTC, bsoufflet requested changes

2023-01-29 23:49 UTC, bsoufflet commented on api/controllers/v1/entrance/get-all-snapshots.js
> +  try {
un petit const entranceId = req.params.id rendrait peut etre le code un peu plus lisible ;)

2023-01-29 23:49 UTC, bsoufflet commented on api/controllers/v1/entrance/get-all-snapshots.js
> +    const commentsId = await CommentService.getIdCommentsByEntranceId(
commentIds

2023-01-29 23:49 UTC, bsoufflet commented on api/controllers/v1/entrance/get-all-snapshots.js
> +    const descriptionsId =
descriptionIds

2023-01-29 23:49 UTC, bsoufflet commented on api/controllers/v1/entrance/get-all-snapshots.js
> +        if (result === '400' || result === '500' || result === '404') {
Que se passe t'il le jour où l'on rajoute une erreur "501" dans `getHLocationById` ? Cela cassera ici...
Je serais d'avis de changer le retour de getHLocationById.
Il faudrait retourner un petit objet du type : 
`{error: 500, hLocations: []}` ou `{error: null, hLocations: [obj1, obj2, ...]}`
Au moins on est certain de la signature de cette fonction, c'est prévisible, ...

2023-01-29 23:49 UTC, bsoufflet commented on api/controllers/v1/entrance/get-all-snapshots.js
> +    const hEntrance = await EntranceService.getHEntrancesById(
il peut y en avoir plusieurs ? -> hEntrances

2023-01-29 23:49 UTC, bsoufflet commented on api/services/DocumentService.js
> +  WITH RECURSIVE recursiveChildren AS (SELECT *
Pas certain de l'utilisé de ce changement ... C'est prettier qui a fait cela ?

2023-01-29 23:49 UTC, bsoufflet commented on api/services/DocumentService.js
> +            DescriptionService.compareDescriptionDate(
Dans DescriptionService pourrais tu ajouter un commentaire de description à compareDescriptionDate ?

2023-01-29 23:49 UTC, bsoufflet commented on api/services/DocumentService.js
> +              new Date(document.id),
l'id n'est ici pas un "Vrai" document ID" mais l'ID tel que defini dans le model Sails. Il faudrait peut etre le préciser...

2023-01-29 23:49 UTC, bsoufflet commented on api/services/DocumentService.js
> +    documentH.forEach((document) => {
documentH est une liste de documentH ? Dans ce cas : documentHList ou hDocuments plutot comme nom.

2023-01-29 23:49 UTC, bsoufflet commented on api/services/DocumentService.js
> +  getHDocumentWithDescritpion: async (documentId, documentH) => {
Si cette fonction ne "get" pas de HDocument mais ne fait que les complété je changerai le nom en "populateHDocumentsWithDescription"

2023-01-29 23:49 UTC, bsoufflet commented on config/routes.js
> +  'GET /api/v1/entrances/:id/all-snapshots': 'v1/entrance/get-all-snapshots',
swagger ?

2023-01-30 08:46 UTC, CecileDestIG commented on api/services/DocumentService.js
> +  WITH RECURSIVE recursiveChildren AS (SELECT *
Oui c'est bien prettier qui a fait le changement

2023-02-01 00:07 UTC, bsoufflet commented on api/services/DocumentService.js
> +            DescriptionService.compareDescriptionDate(
C'est un commentaire sur la fonction  compareDescriptionDate dans le fichier DescriptionService que j'aurais préféré car au moins l'explication servira pour tous les usages... Si vous pouvez le faire plus tard ce serait top ;)

2023-02-01 00:14 UTC, bsoufflet requested changes

2023-02-01 00:14 UTC, bsoufflet commented on api/services/EntranceService.js
> +        if (isEntranceSensitive === 'true') {
isEntranceSensitive est un string ici et pas un boolean ?

2023-02-01 00:14 UTC, bsoufflet commented on api/services/EntranceService.js
> +        if (isEntranceSensitive === 'true') {
ligne 123 vous y assigné un "vrai" bool il semble...
Je préfère qu'un boolean soit un boolean et pas un string perso ;)

2023-02-01 09:26 UTC, bsoufflet commented
Un test à faire passer @CecileDestIG et ce sera bon pour merge ;)

2023-02-01 13:04 UTC, bsoufflet approved these changes

2023-02-01 13:04 UTC, merged