feat(HomepageData): get nb countries and cumulated length
GrottoCenter/grottocenter-api pull request #1117
Opened 2023-02-01 14:42 UTC by MargotGeorget

## 🤔 What

Added request to get the number of countries available in the web site and the cumulated length of all caves.

2023-02-01 22:47 UTC, bsoufflet requested changes

2023-02-01 22:47 UTC, bsoufflet commented on api/controllers/v1/cave/cumulated-length.js
> +      controllerMethod: 'ContryController.count',
probleme ici non ? Contry ?

2023-02-01 22:47 UTC, bsoufflet commented on api/controllers/v1/cave/cumulated-length.js
> +      { value, nb_data: nbData },
Ce ne serait pas mieux de nommé également la property "value" si tu nommes "nb_data" ?

2023-02-01 22:47 UTC, bsoufflet commented on api/controllers/v1/country/count.js
> +      controllerMethod: 'ContryController.count',
Contry

2023-02-01 22:47 UTC, bsoufflet commented on api/services/CaveService.js
> +  SELECT SUM(c.length) as value, COUNT(c.length) as nb_data
value -> sum_length par exemple, c'est plus parlant non ?

2023-02-01 22:47 UTC, bsoufflet commented on api/services/CaveService.js
> +  WHERE c.length IS NOT NULL
Il faudrait filtrer les cave et les entrance qui sont deleted aussi non ?

2023-02-01 22:47 UTC, bsoufflet commented on api/services/CountryService.js
> +    JOIN t_entrance e ON e.id_country = c.iso) as tmp;
is_deleted à prendre en compte aussi ?

2023-02-02 09:36 UTC, MargotGeorget commented on api/controllers/v1/cave/cumulated-length.js
> +      { value, nb_data: nbData },
C'est à dire : {value: value, nb_data: nbData } ?

2023-02-02 21:21 UTC, bsoufflet approved these changes

2023-02-02 21:21 UTC, merged