Replaces rights with a static groups system
GrottoCenter/grottocenter-api pull request #1231
Opened 2023-07-22 13:44 UTC by vmarseguerra

## Converts the rights + groups system to a groups only system

The change was made to resolve the difference between the front and the api:
The front only has groups no concept of rights and base the UI layout on it. So after a change of rights in the database, the front UI is broken until it is adapted. Also changing the front to use a dynamic right system was not worth the effort given how rarely the right needs to be changed. So the API was adapted to use the same groups only system which is simpler and so easier to maintain. However now, if a change of right is wanted a code change is required in the API and in the front.

Groups have no inheritance or order. They can be seen as only providing additional rights to a user. Users can be a member of no, one or multiple groups. Rights for each endpoints should not have changed, only the system that enforces them has changed.
As a reminder, here is a summary of what each groups allows:
- Administrator:
    - Allow to change group membership of any users
    - Can remove the sensitive flag on entrances
    - Have no rate limit
- Moderator:
    - Can remove entities
    - Can validate documents
    - Can handle document and entrance duplicate
    - Can edit any comments
    - Higher ratelimit
- Leader:
    - Can subscribe to massifs and countries
    - Can download the DB export

Like before, the requirements for a route to be accessed by anyone or only logged users is done using sails policy. To avoid redundancy only the `tokenAuth` policy has been kept, verification of group membership is done in the code of each controllers.
Roughly, visitors can only get entities data while logged users can also create and update them.

In the database, the old `Visitor` and `User` group where left but are no more used. Can they also be removed ?

To ease the review, reviewers can you this SQL query to retrieve all previous rights associated with their groups:
```
SELECT t_group.name, t_right.name
FROM t_group
JOIN j_group_right ON t_group.id = j_group_right.id_group
JOIN t_right ON t_right.id = j_group_right.id_right
ORDER BY t_group.name, t_right.name;
```

2023-07-22 13:53 UTC, urien commented
Super clair.
Les Leaders ont un rate limit supérieur a celui des Users mais inférieur aux modérateurs. de manière a leur offrir un service supplémentaire
Les modérateurs peuvent aussi faire l'import en masse via CSV de documents et d'entrées. Je pense qu'il serait préférable de garder cette fonctionnalité aux admins car c'est un outil qui peut avoir un impact assez important sur la base

2023-07-22 14:00 UTC, Clm-Roig commented
@vmarseguerra The production database rights: 

|Group Name|Right name|
|----|----|
|Administrator|Application - delete any|
|Administrator|Application - edit any|
|Administrator|Application - no moderator delete request limit|
|Administrator|Application - no request limit|
|Administrator|Application - no user delete request limit|
|Administrator|Application - view any|
|Administrator|Caver - delete any|
|Administrator|Caver - edit any|
|Administrator|Comment - edit any|
|Administrator|Document - delete any|
|Administrator|Entrance - unmark as sensitive|
|Administrator|Entrance - view complete|
|Administrator|Group - delete any|
|Administrator|Group - edit any|
|Administrator|Group - view any|
|Administrator|Right - delete any|
|Administrator|Right - edit any|
|Administrator|Right - view any|
|Moderator|Application - no request limit|
|Moderator|Application - no user delete request limit|
|Moderator|Application - view any|
|Moderator|Cave - delete any|
|Moderator|Cave - unlink resource|
|Moderator|Comment - edit any|
|Moderator|Document - csv import|
|Moderator|Document Duplicate - create|
|Moderator|Document Duplicate - delete any|
|Moderator|Document - edit not validated|
|Moderator|Entrance - csv import|
|Moderator|Entrance - delete any|
|Moderator|Entrance Duplicate - create|
|Moderator|Entrance Duplicate - delete any|
|Moderator|Entrance - unlink resource|
|Moderator|Group - view any|
|Moderator|Massif - delete any|
|Moderator|Organization - delete any|
|Moderator|Right - view any|
|User|Application - no request limit|
|User|Cave - create|
|User|Cave - edit any|
|User|Cave - link resource|
|User|Cave - merge|
|User|Caver - create|
|User|Caver - delete own|
|User|Caver - edit own|
|User|Caver - view any|
|User|Caver - view complete|
|User|Cave - view any|
|User|Comment - create|
|User|Comment - edit own|
|User|Country - subscribe|
|User|Description - create|
|User|Description - edit any|
|User|Document - create|
|User|Document - edit any|
|User|Document - view any|
|User|Entrance - create|
|User|Entrance - edit any|
|User|Entrance - link resource|
|User|Entrance - mark as sensitive|
|User|Entrance - view limited|
|User|History - create|
|User|History - edit any|
|User|Location - create|
|User|Location - edit any|
|User|Massif - create|
|User|Massif - edit any|
|User|Massif - subscribe|
|User|Massif - view any|
|User|Name - edit any|
|User|Organization - create|
|User|Organization - edit any|
|User|Organization - view any|
|User|Rigging - create|
|User|Rigging - edit any|
|Visitor|Caver - view any|
|Visitor|Document - view any|

2023-07-22 14:01 UTC, Clm-Roig commented
I'm completely changing the rate limit functions in #1223. I will adapt my code to use yours (instead of the old ones) of course.

2023-07-22 14:15 UTC, vmarseguerra commented
@urien  C'est modifié, les imports de CSV sont maintenant réservés aux administrateurs

@Clm-Roig Ok top, j'ai modifié la description pour rediriger vers l'issue et le PR qui modifie les rates limit

2023-07-22 14:38 UTC, urien commented
Merci beaucoup 👍

2023-07-27 09:41 UTC, Clm-Roig commented on api/responses/forbidden.js
> +module.exports = function forbidden(data = 'Request forbidden') {
'Forbidden request'

2023-07-27 09:44 UTC, Clm-Roig commented on sql/2_2021_09_22_1_groups.sql
Visitor group can be deleted I think

2023-07-27 09:45 UTC, Clm-Roig commented on test/integration/4_routes/Caves/delete.test.js
> +    adminToken = await AuthTokenService.getRawBearerModeratorToken();
Something is wrong here. Either rename the variable or change the token type no ?

2023-07-27 09:46 UTC, Clm-Roig commented on test/integration/4_routes/Comments/update.test.js
> +  let userTokenModerator;
`moderatorToken` instead ?

2023-07-27 09:50 UTC, Clm-Roig commented on api/controllers/v1/comment/update.js
> +          'You are not authorized to update any/own comment.'
`You are not authorized to update **any** comment.` dans ce if il me semble.

2023-07-27 09:51 UTC, Clm-Roig commented on api/controllers/v1/document-duplicate/find-all.js
> +      'You are not authorized to find all documents duplicate.'
`document duplicates`

2023-07-27 10:18 UTC, Clm-Roig commented on api/controllers/v1/entrance/update.js
> +      !newIsSensitiveValue
Ici tu veux dire `newIsSensitiveValue === false` si j'ai bien compris ? Je trouve ça plus clair plutôt que de simplement mettre `!newIsSensitiveValue`.

2023-07-27 10:20 UTC, Clm-Roig requested changes
Je refuse juste pour des changements mineurs assez peu impactants au final.

Mais sinon super boulot !

2023-08-12 19:09 UTC, Clm-Roig approved these changes

2023-08-13 09:16 UTC, merged