feat(#977): route to create/update rigging and comment
GrottoCenter/grottocenter-api pull request #978
Opened 2022-08-17 00:29 UTC by bsoufflet

2022-08-17 12:47 UTC, Clm-Roig requested changes

2022-08-17 12:47 UTC, Clm-Roig commented on api/controllers/v1/comment/create.js
> +        'A server error occurred when checking your right to create an comment.'
`an comment` => `a comment`

2022-08-17 12:47 UTC, Clm-Roig commented on api/controllers/v1/comment/create.js
> +    return res.forbidden('You are not authorized to create an comment.');
`an comment` => `a comment`

2022-08-17 12:47 UTC, Clm-Roig commented on api/controllers/v1/comment/update.js
> +    !(await sails.helpers.checkIfExists.with({
Pour que ce soit moins verbeux, tu peux faire `const { checkIfExists } = sails.helpers;` en haut du fichier si tu veux. Ça pourrait être un refacto pertinent pour l'ensemble de l'API d'ailleurs.

2022-08-17 12:47 UTC, Clm-Roig commented on api/controllers/v1/rigging/create.js
> +        'A server error occurred when checking your right to create an rigging.'
`an rigging` => `a rigging`

2022-08-17 12:47 UTC, Clm-Roig commented on api/controllers/v1/rigging/create.js
> +  }
Est-ce que ça ne mériterait pas un refacto dans un `RequestService` ce bout de code ? Il est très utile et on va être amené à s'en servir de plus en plus.

2022-08-17 12:47 UTC, Clm-Roig commented on api/controllers/v1/rigging/create.js
> +  }
Refactoring ? (cf commentaire précédent)
Voir #717

2022-08-17 12:47 UTC, Clm-Roig commented on api/services/MappingService.js
> +    result.approach = source.approach;
Je préfère par ordre alphabétique personnellement.

2022-08-17 12:47 UTC, Clm-Roig commented on api/services/RightService.js
> +    RIGGING: 'Rigging',
Conserver l'ordre alphabétique éventuellement

2022-08-18 23:55 UTC, bsoufflet commented on api/controllers/v1/rigging/create.js
> +  }
TODO ajouté dans le code et commentaire dans #717

2022-08-18 23:56 UTC, bsoufflet commented on api/controllers/v1/rigging/create.js
> +  }
TODO ajouté dans le code...

2022-08-18 23:56 UTC, bsoufflet commented on api/services/MappingService.js
> +    result.approach = source.approach;
ok

2022-08-18 23:56 UTC, bsoufflet commented on api/services/RightService.js
> +    RIGGING: 'Rigging',
ok

2022-08-19 08:11 UTC, Clm-Roig approved these changes

2022-08-22 23:23 UTC, merged